[package]
name = "insults"
version = "0.1.0"
authors = ["Alan Ennis <ennisala@ie.ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
